baseurl = "https://DeepHorizons.github.io/"
languageCode = "en-us"
title = "Joshua Milas"
theme = "vienna"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    github = "DeepHorizons"
    linkedin = "joshuamilas"
	mathjax = true
	mathjax_inline_equations = true

[permalinks]
      post = "/:year/:month/:day/:title/"
